config/routes.rb
Rails.application.routes.draw do
  resources :pets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet.rb
class Pet < ApplicationRecord
  SPECIES = %w[dog cat snake fish bird husband].freeze
  validates :name, presence: true
  validates :species, inclusion: { in: SPECIES }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: %i[show edit update destroy]

  def index
    @pets = Pet.all
  end

  def show; end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    if @pet.save
      redirect_to @pet
      # redirect_to pet_path(@pet)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @pet.update(pet_params)
      redirect_to @pet
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @pet.destroy
    redirect_to pets_path, status: :see_other
  end

  private

  def set_pet
    @pet = Pet.find(params[:id])
  end

  def pet_params
    params.require(:pet).permit(:name, :address, :species, :found_on)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
  def species_icon(species)
    case species
    when 'husband'
      '<i class="fa-solid fa-person"></i>'
    when 'dog'
      '<i class="fa-solid fa-dog"></i>'
    when 'cat'
      '<i class="fa-solid fa-cat"></i>'
    when 'fish'
      '<i class="fa-solid fa-fish"></i>'
    when 'snake'
      '<i class="fa-solid fa-staff-snake"></i>'
    when 'bird'
      '<i class="fa-solid fa-dove"></i>'
    else
      '<i class="fa-solid fa-x"></i>'
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
  <%= simple_form_for(pet) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :species, collection: Pet::SPECIES %>
  <%= f.input :found_on %>
  <%= f.submit class: 'btn btn-sm btn-success' %>
<% end %>

app/views/pets/edit.html.erb
<div class="container">
  <h2>Edit <%= @pet.name %></h2>
  <%= render 'form', pet: @pet %>
</div>

<div class="container my-3">
  <%= link_to pet_path(@pet), class: 'btn btn-sm btn-success' do %>
    <i class="fa-solid fa-backward"></i>
  <% end %>
</div>

app/views/pets/index.html.erb
<div class="container">
  <h1>Lost Pets</h1>
  <%= link_to 'Add new pet', new_pet_path, class: 'btn btn-sm btn-success' %>
  <hr>

  <% @pets.each do |pet| %>
    <p>
      <%= link_to pet_path(pet), class: 'text-decoration-none' do %>
        <%= pet.name %> <small>(<%= species_icon(pet.species).html_safe %>)</small>
      <% end %>
    </p>
  <% end %>
</div>

app/views/pets/new.html.erb
<div class="container">
  <h2>New pet</h2>

  <%= render 'form', pet: @pet %>
</div>

<div class="container my-3">
  <%= link_to pets_path, class: 'btn btn-sm btn-success' do %>
    <i class="fa-solid fa-backward"></i>
  <% end %>
</div>

app/views/pets/show.html.erb
<div class="container">
  <h2><%= @pet.name %></h2>

  <p>Species: <%= @pet.species %></p>
  <p>Address: <%= @pet.address %></p>
  <p>Found on: <%= @pet.found_on.strftime('%d/%m/%Y') %></p>

  <%= link_to pets_path, class: 'btn btn-sm btn-success' do %>
    <i class="fa-solid fa-backward"></i>
  <% end %>
  <%= link_to edit_pet_path(@pet), class: 'btn btn-sm btn-warning' do %>
    <i class="fa-solid fa-pen-to-square"></i>
  <% end %>
  <%= link_to pet_path(@pet),
    data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'},
    class: 'btn btn-sm btn-danger' do %>
    <i class="fa-solid fa-trash"></i>
  <% end %>
</div>